# Generated by Django 5.2.7 on 2025-10-30 00:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='CategoriasAjustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'categorias_ajustes',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='AjusteRazonable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('categorias_ajustes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.categoriasajustes')),
            ],
            options={
                'db_table': 'ajuste_razonable',
            },
        ),
        migrations.CreateModel(
            name='DirectoresCarreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.areas')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.roles')),
            ],
            options={
                'db_table': 'directores_carreras',
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=191)),
                ('directores_carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.directorescarreras')),
            ],
            options={
                'db_table': 'carreras',
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.areas')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.roles')),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('seccion', models.CharField(max_length=150)),
                ('carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.carreras')),
                ('docentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.docentes')),
            ],
            options={
                'db_table': 'asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=191)),
                ('apellidos', models.CharField(max_length=191)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('numero', models.IntegerField(blank=True, default='', null=True)),
                ('carreras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.carreras')),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='AsignaturasEnCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('asignaturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.asignaturas')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.estudiantes')),
            ],
            options={
                'db_table': 'asignaturas_en_curso',
            },
        ),
        migrations.CreateModel(
            name='AsesoresPedagogicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.roles')),
            ],
            options={
                'db_table': 'asesores_pedagogicos',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asesores_pedagogicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.asesorespedagogicos')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.estudiantes')),
            ],
            options={
                'db_table': 'solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('estudiantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.estudiantes')),
                ('solicitudes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.solicitudes')),
            ],
            options={
                'db_table': 'evidencias',
            },
        ),
        migrations.CreateModel(
            name='Entrevistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('modalidad', models.CharField(max_length=100)),
                ('notas', models.TextField()),
                ('asesores_pedagogicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.asesorespedagogicos')),
                ('solicitudes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.solicitudes')),
            ],
            options={
                'db_table': 'entrevistas',
            },
        ),
        migrations.CreateModel(
            name='AjusteAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajuste_razonable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.ajusterazonable')),
                ('solicitudes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIAPE.solicitudes')),
            ],
            options={
                'db_table': 'ajuste_asignado',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('numero', models.IntegerField(blank=True, default='', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='docentes',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directorescarreras',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asesorespedagogicos',
            name='usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
