# Generated by Django 5.2.7 on 2025-10-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
