# Generated by Django 4.2.25 on 2025-10-31 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreras',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras', to='SIAPE.areas'),
        ),
    ]
