# Generated by Django 5.2.7 on 2025-10-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0002_alter_estudiantes_numero_alter_usuario_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorescarreras',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='docentes',
            name='rol',
        ),
    ]
