# Generated by Django 4.2.25 on 2025-10-31 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0002_carreras_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='asesor_pedagogico',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='asesores_pedagogicos',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Asesor Pedagogico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIAPE.perfilusuario'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='asignaturas_solicitadas',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_de_ajuste', to='SIAPE.asignaturas'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='autorizacion_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
