# Generated by Django 4.2.25 on 2025-10-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0003_remove_solicitudes_asesor_pedagogico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaturasencurso',
            name='estado',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado de la Asignatura'),
        ),
    ]
