# Generated by Django 4.2.25 on 2025-11-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0004_alter_asignaturasencurso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
