# Generated by Django 5.2.7 on 2025-11-04 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0005_alter_solicitudes_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_proceso', max_length=20, verbose_name='Estado de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='asesores_pedagogicos',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Asesor Pedagógico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIAPE.perfilusuario'),
        ),
    ]
