# Generated by Django 5.2.7 on 2025-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0007_rename_fecha_entrevistas_fecha_entrevista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistas',
            name='notas',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
