# Generated by Django 5.2.7 on 2025-11-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0008_alter_entrevistas_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20, verbose_name='Estado de la Entrevista'),
        ),
    ]
