# Generated by Django 5.2.7 on 2025-11-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0009_add_estado_entrevistas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevistas',
            name='asesor_pedagogico',
        ),
        migrations.AddField(
            model_name='entrevistas',
            name='coordinadora',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Coordinadora de Inclusión'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIAPE.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='entrevistas',
            name='estado',
            field=models.CharField(choices=[('pendiente_entrevista', 'Pendiente de Entrevista (Coordinadora)'), ('pendiente_formulacion', 'Pendiente de Formulación (Asesora Técnica)'), ('pendiente_aprobacion', 'Pendiente de Aprobación (Director)'), ('aprobado', 'Aprobado e Informado'), ('rechazado', 'Rechazado')], default='pendiente_entrevista', max_length=30, verbose_name='Estado de la Solicitud'),
        ),
    ]
