# Generated by Django 5.2.7 on 2025-11-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0010_remove_entrevistas_asesor_pedagogico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevistas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='asesores_pedagogicos',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='asesor_pedagogico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Asesor Pedagógico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_asesor_pedagogico', to='SIAPE.perfilusuario'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='asesor_tecnico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Asesora Técnica'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_asesor_tecnico', to='SIAPE.perfilusuario'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='coordinadora_asignada',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Coordinadora de Inclusión'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_coordinadora', to='SIAPE.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('pendiente_entrevista', 'Pendiente de Entrevista (Coordinadora)'), ('pendiente_formulacion', 'Pendiente de Formulación (Asesora Técnica)'), ('pendiente_preaprobacion', 'Pendiente de Preaprobación (Asesor Pedagógico)'), ('pendiente_aprobacion', 'Pendiente de Aprobación (Director)'), ('aprobado', 'Aprobado e Informado'), ('rechazado', 'Rechazado')], default='pendiente_entrevista', max_length=30, verbose_name='Estado de la Solicitud'),
        ),
    ]
