# Generated by Django 5.2.7 on 2025-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0011_remove_entrevistas_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20, verbose_name='Estado de la Entrevista'),
        ),
    ]
