# Generated by Django 5.2.7 on 2025-11-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0012_entrevistas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('pendiente_entrevista', 'Pendiente de Entrevista (Coordinadora)'), ('pendiente_formulacion_caso', 'Pendiente de Formulación del Caso (Coordinadora)'), ('pendiente_formulacion', 'Pendiente de Formulación de Ajustes (Asesora Técnica)'), ('pendiente_preaprobacion', 'Pendiente de Preaprobación (Asesor Pedagógico)'), ('pendiente_aprobacion', 'Pendiente de Aprobación (Director)'), ('aprobado', 'Aprobado e Informado'), ('rechazado', 'Rechazado')], default='pendiente_entrevista', max_length=30, verbose_name='Estado de la Solicitud'),
        ),
    ]
