# Generated by Django 5.2.7 on 2025-11-13 00:33

from django.db import migrations, models


def actualizar_estados_pendiente_formulacion(apps, schema_editor):
    """
    Migración de datos: actualizar registros existentes de 'pendiente_formulacion' 
    a 'pendiente_formulacion_ajustes'
    """
    Solicitudes = apps.get_model('SIAPE', 'Solicitudes')
    Solicitudes.objects.filter(estado='pendiente_formulacion').update(estado='pendiente_formulacion_ajustes')


def revertir_estados_pendiente_formulacion(apps, schema_editor):
    """
    Migración reversa: volver a cambiar 'pendiente_formulacion_ajustes' 
    a 'pendiente_formulacion'
    """
    Solicitudes = apps.get_model('SIAPE', 'Solicitudes')
    Solicitudes.objects.filter(estado='pendiente_formulacion_ajustes').update(estado='pendiente_formulacion')


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0013_add_pendiente_formulacion_caso_estado'),
    ]

    operations = [
        # Primero actualizar los datos existentes
        migrations.RunPython(actualizar_estados_pendiente_formulacion, revertir_estados_pendiente_formulacion),
        # Luego actualizar el esquema del campo
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('pendiente_entrevista', 'Pendiente de Entrevista (Coordinadora)'), ('pendiente_formulacion_caso', 'Pendiente de Formulación del Caso (Coordinadora)'), ('pendiente_formulacion_ajustes', 'Pendiente de Formulación de Ajustes (Asesora Técnica)'), ('pendiente_preaprobacion', 'Pendiente de Preaprobación (Asesor Pedagógico)'), ('pendiente_aprobacion', 'Pendiente de Aprobación (Director)'), ('aprobado', 'Aprobado e Informado'), ('rechazado', 'Rechazado')], default='pendiente_entrevista', max_length=30, verbose_name='Estado de la Solicitud'),
        ),
    ]
