# Generated by Django 5.2.7 on 2025-11-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0014_rename_pendiente_formulacion_to_pendiente_formulacion_ajustes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteasignado',
            name='comentarios_director',
            field=models.TextField(blank=True, default='', verbose_name='Comentarios del Director'),
        ),
        migrations.AddField(
            model_name='ajusteasignado',
            name='director_aprobador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Director de Carrera'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_aprobados', to='SIAPE.perfilusuario', verbose_name='Director que Aprobó/Rechazó'),
        ),
        migrations.AddField(
            model_name='ajusteasignado',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Aprobación'),
        ),
        migrations.AddField(
            model_name='ajusteasignado',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación/Rechazo'),
        ),
    ]
