# Generated by Django 5.2.7 on 2025-11-13 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0015_ajusteasignado_comentarios_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora Bloqueada')),
                ('motivo', models.CharField(blank=True, default='', help_text='Ej: Reunión, Capacitación, etc.', max_length=255, verbose_name='Motivo del Bloqueo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinadora', models.ForeignKey(limit_choices_to={'rol__nombre_rol': 'Coordinadora de Inclusión'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bloqueados', to='SIAPE.perfilusuario', verbose_name='Coordinadora')),
            ],
            options={
                'verbose_name': 'Horario Bloqueado',
                'verbose_name_plural': 'Horarios Bloqueados',
                'db_table': 'horarios_bloqueados',
                'unique_together': {('coordinadora', 'fecha_hora')},
            },
        ),
    ]
