# Generated by Django 5.2.7 on 2025-12-07 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0016_add_horarios_bloqueados_and_ajuste_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='semestre_actual',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], help_text='Semestre actual del estudiante (1-8)', null=True, verbose_name='Semestre Actual'),
        ),
        migrations.AlterField(
            model_name='entrevistas',
            name='coordinadora',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Encargado de Inclusión'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='SIAPE.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='horariobloqueado',
            name='coordinadora',
            field=models.ForeignKey(limit_choices_to={'rol__nombre_rol': 'Encargado de Inclusión'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_bloqueados', to='SIAPE.perfilusuario', verbose_name='Encargado de Inclusión'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='asesor_tecnico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Coordinador Técnico Pedagógico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_asesor_tecnico', to='SIAPE.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='coordinadora_asignada',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Encargado de Inclusión'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_coordinadora', to='SIAPE.perfilusuario'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(choices=[('pendiente_entrevista', 'Pendiente de Entrevista (Encargado de Inclusión)'), ('pendiente_formulacion_caso', 'Pendiente de Formulación del Caso (Encargado de Inclusión)'), ('pendiente_formulacion_ajustes', 'Pendiente de Formulación de Ajustes (Coordinador Técnico Pedagógico)'), ('pendiente_preaprobacion', 'Pendiente de Preaprobación (Asesor Pedagógico)'), ('pendiente_aprobacion', 'Pendiente de Aprobación (Director)'), ('aprobado', 'Aprobado e Informado'), ('rechazado', 'Rechazado')], default='pendiente_entrevista', max_length=30, verbose_name='Estado de la Solicitud'),
        ),
    ]
