# Generated by Django 5.2.7 on 2025-12-07 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0017_estudiantes_semestre_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteasignado',
            name='comentarios_docente',
            field=models.TextField(blank=True, default='', verbose_name='Comentarios del Docente'),
        ),
        migrations.AddField(
            model_name='ajusteasignado',
            name='docente_comentador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_comentados', to='SIAPE.perfilusuario', verbose_name='Docente que Comentó'),
        ),
        migrations.AddField(
            model_name='ajusteasignado',
            name='fecha_comentario_docente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Comentario del Docente'),
        ),
    ]
