# Generated by Django 5.2.7 on 2025-12-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0018_ajusteasignado_comentarios_docente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='asesor_tecnico_asignado',
            new_name='coordinador_tecnico_pedagogico_asignado',
        ),
    ]
