# Generated by Django 5.2.7 on 2025-12-11 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0019_rename_asesor_tecnico_to_coordinador_tecnico_pedagogico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='coordinador_tecnico_pedagogico_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol__nombre_rol': 'Coordinador Técnico Pedagógico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_coordinador_tecnico_pedagogico', to='SIAPE.perfilusuario'),
        ),
    ]
