# Generated by Django 5.2.7 on 2025-12-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIAPE', '0020_alter_solicitudes_coordinador_tecnico_pedagogico_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturas',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desactivar al finalizar el semestre', verbose_name='Asignatura Activa'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='semestre',
            field=models.CharField(blank=True, choices=[('otono', 'Otoño (Marzo-Julio)'), ('primavera', 'Primavera (Agosto-Diciembre)')], max_length=20, null=True, verbose_name='Semestre'),
        ),
    ]
